### PR TITLE
Interactive list

### PR DESCRIPTION
**Pull request by ahzia**
In this pull request, I have worked on Making the Project more interactive by adding draggable support and storing todos in local storage.
Kindly review it and share your feedbacks with me.
Thanks

### CODE REVIEW

**Review by vichuge — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [x] When I tried to make changes on the list and refresh the pages, the changes don't appear. I think is something with `localStorage`. I kindly invite you to work on it.
image


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ahzia** [comment]
@vichuge thanks for your review.
(When I tried to make changes to the list) - what specific changes you did? was the problem with updating checkbox status(complete/not complete) or dragging items?
I have checked on my side everything is working fine,can you tell me More details?
Note: If by changes you mean updating to-do lists on code You need to clear local storage and refresh the page because when local storage is not Null, I have taken todos from local storage not the static todo list in code.

**Comment by SpaYco** [comment]
Hello 👋,

_This is an additional review as a result of the second opinion request._

I tested the project on my end, and everything works fine.

Due to CRs reviewing the same project by different students, I think localStorage is giving false data which can cause this issue, we'll see what we can do to remove cases like this

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approve right away :)

Keep rocking 🚀!

**Comment by mricanho** [comment]
# Status: ✔️ Project Approved ✔️ 

Hello @ahzia  🔥 

Nicely done, your app it's up and running, you can continue to the next milestone👍🏽 

yougotit

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
